// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPHAdxKgOoJ-HkK6jba9J-XW_hZK8y47g',
    appId: '1:640784192190:web:1a0f89e08bcdc73f2d84ef',
    messagingSenderId: '640784192190',
    projectId: 'aws-db-e1c2d',
    authDomain: 'aws-db-e1c2d.firebaseapp.com',
    storageBucket: 'aws-db-e1c2d.appspot.com',
    measurementId: 'G-N4FB5W71S8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy5xjek6eowa7ZOCxuDaygKWE93xxbpfE',
    appId: '1:640784192190:android:9ce7926bb9339b472d84ef',
    messagingSenderId: '640784192190',
    projectId: 'aws-db-e1c2d',
    storageBucket: 'aws-db-e1c2d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByIr7hlSnJNVJs893ENY_Yobnyz1V8i5I',
    appId: '1:640784192190:ios:f0fecf8e435980fe2d84ef',
    messagingSenderId: '640784192190',
    projectId: 'aws-db-e1c2d',
    storageBucket: 'aws-db-e1c2d.appspot.com',
    iosBundleId: 'com.airwise.integradora.airwisesystems',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPHAdxKgOoJ-HkK6jba9J-XW_hZK8y47g',
    appId: '1:640784192190:web:b7c80081985f79372d84ef',
    messagingSenderId: '640784192190',
    projectId: 'aws-db-e1c2d',
    authDomain: 'aws-db-e1c2d.firebaseapp.com',
    storageBucket: 'aws-db-e1c2d.appspot.com',
    measurementId: 'G-DCR45X2TB3',
  );
}
